version: '3'

services:
  db:
    image: postgres:16.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 15432:5432
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwpostgres!
volumes:
  pgdata: